version: "3.8"

services:
  api:
    build: ./
    restart: always
    command: uvicorn server:app --reload --workers 1 --host 0.0.0.0 --port 8087
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "8087:8087"
    volumes:
      - ./src/:/src/

networks:
  backend: